name: Test

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Build track_syscalls
        run: |
          sudo apt-get -y install llvm libbpfcc-dev libbpf-dev linux-headers-$(uname -r)
          (cd track_syscalls && make all)

      - name: Build test packages
        run: (cd testpkgs && make build)

      - name: Run tests
        run: (cd track_syscalls && sudo go test)
